local E, L, V, P, G,_ = unpack(ElvUI)
local AS = E:GetModule('AddOnSkins')
local S = E:GetModule('Skins')

local name = "EveryGoldToBankerSkin"
function AS:SkinEveryGoldToBanker()
	AS:SkinFrame(EveryGoldToBankerCalculator)
	AS:SkinFrame(SettingFrame)
	S:HandleEditBox(AmountEditBox)
	AmountEditBox:Height(22)
	S:HandleEditBox(ReceiverEditBox)
	ReceiverEditBox:Height(22)
	S:HandleEditBox(DefaultAmountEditBox)
	DefaultAmountEditBox:Height(22)
	S:HandleEditBox(DefaultReceiverEditBox)
	DefaultReceiverEditBox:Height(22)
	S:HandleButton(CheckButton)
	S:HandleButton(SendButton)
	S:HandleButton(SettingButton)
	S:HandleButton(DoneSettingButton)
	TitleFrame:StripTextures()
	AmountFrame:StripTextures()
	ResponseFrame:StripTextures()
	ReceiverFrame:StripTextures()
	DefaultAmountFrame:StripTextures()
	DefaultReceiverFrame:StripTextures()
end
AS:RegisterSkin(name, AS.SkinEveryGoldToBanker)