local AS = unpack(AddOnSkins)

if not AS:CheckAddOn('QuikEmotes') then return end

function AS:QuikEmotes()
	AS:SkinFrame(Group1)
	AS:SkinButton(Button1)
	AS:SkinButton(Button2)
	AS:SkinButton(Button3)
	AS:SkinButton(Button4)
	AS:SkinButton(Button5)
	AS:SkinButton(Button6)
	AS:SkinButton(Button7)
	AS:SkinButton(Button8)
	AS:SkinButton(Button9)
	AS:SkinButton(Button10)
	AS:SkinButton(Button11)
	AS:SkinButton(Button12)
	AS:SkinButton(Button13)
	AS:SkinButton(Button14)
	AS:SkinButton(Button15)
	AS:SkinButton(Button16)
	AS:SkinButton(Button17)
	AS:SkinButton(Button18)
	AS:SkinButton(Button19)
	AS:SkinButton(Button20)
	AS:SkinButton(Button21)
	AS:SkinButton(Button22)
	AS:SkinFrame(Group2)
	AS:SkinFrame(Select)
	AS:SkinButton(List1)
	AS:SkinButton(List2)
	AS:SkinButton(All)

end

AS:RegisterSkin('QuikEmotes', AS.QuikEmotes)
