local AS, L, S, R = unpack(AddOnSkins)

function R:Tongues()
	S:HandleFrame(Tongues.UI.MainMenu.Frame)
	S:HandleFrame(Tongues.UI.MainMenu.AdvancedOptions.Frame)
	S:HandleButton(Tongues.UI.MiniMenu.Frame)
	Tongues.UI.MiniMenu.Frame:HookScript('OnUpdate', function(self)
		self:SetText("|cFFFFFFFFTongues\10|cff1784d1"..Tongues.Settings.Character.Language)
	end)
	S:HandleButton(Tongues.UI.MainMenu.SpeakButton.Frame)
	S:HandleButton(Tongues.UI.MainMenu.UnderstandButton.Frame)
	S:HandleButton(Tongues.UI.MainMenu.HearButton.Frame)
	S:HandleCloseButton(Tongues.UI.MainMenu.CloseButton.Frame)
	S:HandleDropDownBox(Tongues.UI.MainMenu.Speak.LanguageDropDown.Frame)
	S:HandleDropDownBox(Tongues.UI.MainMenu.Speak.DialectDropDown.Frame)
	S:HandleDropDownBox(Tongues.UI.MainMenu.Speak.AffectDropDown.Frame)
	S:HandleSlideBar(Tongues.UI.MainMenu.Speak.AffectFrequency.Frame)
--	S:HandleCheckBox(Tongues.UI.MainMenu.Speak.DialectDrift.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Speak.LanguageLearn.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Speak.ShapeshiftLanguage.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Speak.MiniHide.Frame)
--	S:HandleCheckBox(Tongues.UI.MainMenu.Speak.LoreCompatibility.Frame)
	S:HandleEditBox(Tongues.UI.MainMenu.Understand.Language.Frame)
	S:HandleSlideBar(Tongues.UI.MainMenu.Understand.Fluency.Frame)
	S:HandleButton(Tongues.UI.MainMenu.Understand.UpdateButton.Frame)
	S:HandleButton(Tongues.UI.MainMenu.Understand.ClearLanguagesButton.Frame)
	S:HandleButton(Tongues.UI.MainMenu.Understand.ListLanguagesButton.Frame)
	S:HandleTooltip(Lib_DropDownList1Backdrop)
	S:HandleDropDownBox(Tongues.UI.MainMenu.Hear.Filter.Frame)
	S:HandleButton(Tongues.UI.MainMenu.AdvancedButton.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Translations.Self.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Translations.Targetted.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Translations.Party.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Translations.Guild.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Translations.Officer.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Translations.Raid.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Translations.RaidAlert.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Translations.Battleground.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Screen.Self.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Screen.Targetted.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Screen.Party.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Screen.Guild.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Screen.Officer.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Screen.Raid.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Screen.RaidAlert.Frame)
	S:HandleCheckBox(Tongues.UI.MainMenu.Screen.Battleground.Frame)
	S:HandleEditBox(Tongues.UI.MainMenu.Translators.TranslatorEditbox.Frame)
	S:HandleButton(Tongues.UI.MainMenu.Translators.AddTranslatorButton.Frame)
	S:HandleButton(Tongues.UI.MainMenu.Translators.ClearTranslatorButton.Frame)
	S:HandleButton(Tongues.UI.MainMenu.Translators.ListTranslatorButton.Frame)
	Tongues.UI.MainMenu.Minimize.Frame:SetPoint("TOPLEFT", Tongues.UI.MainMenu.Frame, 2, -2)
	S:CreateBackdrop(Tongues.UI.MainMenu.Minimize.Frame)
	S:HandleIcon(Tongues.UI.MainMenu.Minimize.texture[1])
end

AS:RegisterSkin('Tongues')
